# From: https://github.com/marketplace/actions/cppcheck-action

name: cppcheck-action-test
on:
  push:
    branches: [main]

jobs:
  build:
    name: cppcheck-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        # https://github.com/marketplace/actions/update-git-branch
      - uses: Embraser01/update-git-branch-action@v1.0.0
        with:
          branch: cpp_check
          force: 1 # To push-force to the branch
          githubToken: ${{ secrets.PAT_TOKEN }} # Github Token
          
      - name: cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          
      - name: publish report    
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'cpp_check'