# From: https://github.com/nullromo/doxygen-example/blob/main/.github/workflows/main.yml
name: Doxygen Action

on:
  push:
    branches: [main]
    
permissions: 
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone doxygen-awesome-css
        uses: actions/checkout@v3
        with:
          repository: jothepro/doxygen-awesome-css
          ref: refs/heads/main
          
      - uses: actions/checkout@v3
      - name: Build Doxygen documentation
        uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          doxyfile-path: "./Doxyfile"
          working-directory: "./backend"

      - name: Move Doxygen HTML files into Doxygen directory
        run: |
          sudo mv docs/doxygen/html/* docs/doxygen

      - name: Build JSDoc documentation
        uses: andstor/jsdoc-action@v1
        with:
            config_file: "./frontend/jsdoc.config.json"
            output_dir: './docs/jsdoc'
            recurse: true

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs