# From: https://github.com/nullromo/doxygen-example/blob/main/.github/workflows/main.yml
name: Doxygen Action

on:
  push:
    branches: [main]
    
permissions: 
  contents: write

jobs:
  build_doxygen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build Doxygen documentation for Raspberry Pi
        uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          doxyfile-path: "./Doxyfile"
          working-directory: "./app/rpi"
      
      - name: Build Doxygen documentation for Other Code Projects
        uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          doxyfile-path: "./Doxyfile"
          working-directory: "./app/other"

      - name: Move Doxygen HTML files into their parent directories
        run: |
          sudo mv docs/raspberry_pi/html/* docs/raspberry_pi
          sudo mv docs/other/html/* docs/other

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs

  build_doxygen_pdf:
    needs: build_doxygen
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: gh-pages
      
      - name: Generate Doxygen PDF
        run: |
          sudo apt-get update -y
          sudo apt-get install -y doxygen-latex
          
          cd raspberry_pi/latex
          sudo make

          cd ../..

          cd other/latex
          sudo make

      - name: Commit PDF    
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'gh-pages'
