# From: https://github.com/nullromo/doxygen-example/blob/main/.github/workflows/main.yml
name: Doxygen Action

on:
  push:
    branches: [main]
    
permissions: 
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build Doxygen documentation for Raspberry Pi
        uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          doxyfile-path: "./Doxyfile"
          working-directory: "./app/rpi/common"

      - name: Move Doxygen HTML files into their parent directories
        run: |
          sudo mv docs/raspberry_pi/html/* docs/raspberry_pi

      - name: Generate Doxygen pdf
        run: |
          sudo apt-get install texlive-latex-base
          # sudo apt-get install texlive-fonts-recommended
          # sudo apt-get install texlive-fonts-extra
          sudo apt-get install texlive-latex-extra
          cd docs/raspberry_pi/latex
          sudo make

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs