# From: https://github.com/nullromo/doxygen-example/blob/main/.github/workflows/main.yml
name: Doxygen Action

on:
  push:
    branches: [main]
    
permissions: 
  contents: write

jobs:
  generate_page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Install Eleventy
        run:
          sudo npm install -g @11ty/eleventy

      - name: Build Site and Copy
        run: |
          cd site
          pnpm install
          pnpm run build

      - name: Build Doxygen documentation for Admin Panel
        uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          doxyfile-path: "./Doxyfile"
          working-directory: "./app/admin_panel"
      
      - name: Build Doxygen documentation for Raspberry Pi
        uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          doxyfile-path: "./Doxyfile"
          working-directory: "./app/rpi"
      
      - name: Build Doxygen documentation for Other Code Projects
        uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          doxyfile-path: "./Doxyfile"
          working-directory: "./app/other"

      - name: Move Doxygen HTML files
        run: |
          sudo mv docs/static site/docs
          
          mkdir -p site/_site/docs/admin_panel
          mkdir -p site/_site/docs/raspberry_pi
          mkdir -p site/_site/docs/other

          sudo mv site/docs/admin_panel/html/* site/_site/docs/admin_panel
          sudo mv site/docs/raspberry_pi/html/* site/_site/docs/raspberry_pi
          sudo mv site/docs/other/html/* site/_site/docs/other

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/_site

  build_doxygen_pdf:
    needs: generate_page
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: gh-pages
      
      - name: Generate Doxygen PDF
        run: |
          sudo apt-get update -y
          sudo apt-get install -y doxygen-latex
          
          cd docs/admin_panel/latex
          sudo make

          cd ../../..
          
          cd docs/raspberry_pi/latex
          sudo make

          cd ../../..

          cd docs/other/latex
          sudo make

      - name: Commit PDF    
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'gh-pages'
